"""create studies channels annotations

Revision ID: 0f809e7d8d5f
Revises: 
Create Date: 2026-08-18 11:28:39.274478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f809e7d8d5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('record_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'record_name', name='uq_study_dataset_record')
    )
    op.create_index(op.f('ix_studies_dataset_id'), 'studies', ['dataset_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('onset_sec', sa.Float(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_study_id'), 'annotations', ['study_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('sampling_rate', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_study_id'), 'channels', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_study_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_annotations_study_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_studies_dataset_id'), table_name='studies')
    op.drop_table('studies')
    # ### end Alembic commands ###
