"""add phenotype_labels table

Revision ID: 1d227afb6a20
Revises: b8dd0326af23
Create Date: 2026-08-18 12:20:12.508827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d227afb6a20'
down_revision: Union[str, None] = 'b8dd0326af23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phenotype_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('cluster_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('k', 'cluster_index', name='uq_phenotype_label_k_cluster')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phenotype_labels')
    # ### end Alembic commands ###
