"""add study source and display_name

Revision ID: 7eefb882356e
Revises: 0f809e7d8d5f
Create Date: 2026-08-18 11:43:48.488588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7eefb882356e'
down_revision: Union[str, None] = '0f809e7d8d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('source', sa.String(length=16), nullable=False, server_default='public'))
    op.add_column('studies', sa.Column('display_name', sa.String(length=256), nullable=True))
    op.alter_column('studies', 'source', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'display_name')
    op.drop_column('studies', 'source')
    # ### end Alembic commands ###
