"""add respiratory_events table

Revision ID: b8dd0326af23
Revises: bbfbcc35cc08
Create Date: 2026-08-18 11:58:47.597262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8dd0326af23'
down_revision: Union[str, None] = 'bbfbcc35cc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respiratory_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('onset_sec', sa.Float(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('depth_ratio', sa.Float(), nullable=False),
    sa.Column('spo2_baseline', sa.Float(), nullable=True),
    sa.Column('spo2_nadir', sa.Float(), nullable=True),
    sa.Column('desaturation_depth', sa.Float(), nullable=True),
    sa.Column('desaturation_slope', sa.Float(), nullable=True),
    sa.Column('recovery_sec', sa.Float(), nullable=True),
    sa.Column('eeg_delta_rel', sa.Float(), nullable=True),
    sa.Column('eeg_theta_rel', sa.Float(), nullable=True),
    sa.Column('eeg_alpha_rel', sa.Float(), nullable=True),
    sa.Column('eeg_beta_rel', sa.Float(), nullable=True),
    sa.Column('arousal_probability', sa.Float(), nullable=True),
    sa.Column('hr_baseline_bpm', sa.Float(), nullable=True),
    sa.Column('hr_peak_bpm', sa.Float(), nullable=True),
    sa.Column('hr_response_bpm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respiratory_events_study_id'), 'respiratory_events', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respiratory_events_study_id'), table_name='respiratory_events')
    op.drop_table('respiratory_events')
    # ### end Alembic commands ###
