"""add channel mapping confidence and confirmation

Revision ID: bbfbcc35cc08
Revises: 7eefb882356e
Create Date: 2026-08-18 11:50:27.228814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bbfbcc35cc08'
down_revision: Union[str, None] = '7eefb882356e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('mapping_confidence', sa.Float(), nullable=False, server_default='0'))
    op.add_column('channels', sa.Column('mapping_confirmed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('studies', sa.Column('channel_mapping_confirmed', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('channels', 'mapping_confidence', server_default=None)
    op.alter_column('channels', 'mapping_confirmed', server_default=None)
    op.alter_column('studies', 'channel_mapping_confirmed', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'channel_mapping_confirmed')
    op.drop_column('channels', 'mapping_confirmed')
    op.drop_column('channels', 'mapping_confidence')
    # ### end Alembic commands ###
